package lib

import (
	"fmt"
	"github.com/bwmarrin/discordgo"
	"opb_bot/lib/battlenet"
	"opb_bot/lib/db"
	"opb_bot/lib/raiderio"
	"opb_bot/lib/utils"
	"reflect"
	"strings"
	"time"
)

var (
	server_id             = "701570658919907396"
	test_channel_id       = "879021343981596732"
	free_games_channel_id = "710519845799723090"
)

type BotHandler struct {
	db_instance *db.DBHandler
	Methods     map[string]reflect.Method
	raider      *raiderio.RaiderApi
	battlenet   *battlenet.Battlenet
}

func InitHandler(b_handler *BotHandler, db_instance *db.DBHandler) error {
	b_handler.db_instance = db_instance
	b_handler.Methods = map[string]reflect.Method{}
	t := reflect.TypeOf(b_handler)
	for i := 0; i < t.NumMethod(); i++ {
		m := t.Method(i)
		method_name := strings.ToLower(m.Name)
		command := strings.Replace(method_name, method_name, "/"+method_name, 1)
		b_handler.Methods[command] = m
	}

	b_handler.raider = raiderio.CreateApi()
	token, err := db_instance.GetAccessToken("battlenet")
	if err != nil {
		return err
	}
	if token == "" {
		service, _ := db_instance.GetService("battlenet")
		var battle_net_oauth *battlenet.AutoGeneratedOauthResp
		battle_net_oauth, err = battlenet.GetBattleNetToken(service.Client, service.Secret)
		if err != nil {
			utils.PrintType(err)
			return err

		}
		utils.PrintType(battle_net_oauth)
		expires := time.Now().Add(time.Duration(battle_net_oauth.ExpiresIn))
		err = db_instance.RefreshAccessToken("battlenet", battle_net_oauth.AccessToken, expires)
		if err != nil {
			utils.PrintType(err)
			return err
		}
	}
	return err

}

func HandleIncomingMessage(handler *BotHandler, s *discordgo.Session, m *discordgo.MessageCreate) {
	fmt.Println(m.ChannelID, m.Content)
	fmt.Println("-----------------------")
	method, ok := handler.Methods[m.Content]
	if ok {
		in := []reflect.Value{reflect.ValueOf(handler), reflect.ValueOf(s), reflect.ValueOf(m)}
		method.Func.Call(in)
	}

}

func (handler *BotHandler) _getHelpMessage() (message string) {
	message = "Поддерживаемые команды:\n" +
		"**__/help__** - скоманда показывающая это окно.\n" +
		"**__/egsupdate__** - обновление списка бесплатных игр в Epic Games Store"
	return
}
