package egs

import "time"

type AutoGeneratedEGSResponse struct {
	Data struct {
		Catalog struct {
			SearchStore struct {
				Elements []struct {
					Title                string      `json:"title"`
					ID                   string      `json:"id"`
					Namespace            string      `json:"namespace"`
					Description          string      `json:"description"`
					EffectiveDate        time.Time   `json:"effectiveDate"`
					OfferType            string      `json:"offerType"`
					ExpiryDate           interface{} `json:"expiryDate"`
					Status               string      `json:"status"`
					IsCodeRedemptionOnly bool        `json:"isCodeRedemptionOnly"`
					KeyImages            []struct {
						Type string `json:"type"`
						URL  string `json:"url"`
					} `json:"keyImages"`
					Seller struct {
						ID   string `json:"id"`
						Name string `json:"name"`
					} `json:"seller"`
					ProductSlug string      `json:"productSlug"`
					URLSlug     string      `json:"urlSlug"`
					URL         interface{} `json:"url"`
					Items       []struct {
						ID        string `json:"id"`
						Namespace string `json:"namespace"`
					} `json:"items"`
					CustomAttributes []struct {
						Key   string `json:"key"`
						Value string `json:"value"`
					} `json:"customAttributes"`
					Categories []struct {
						Path string `json:"path"`
					} `json:"categories"`
					Tags []struct {
						ID string `json:"id"`
					} `json:"tags"`
					CatalogNs struct {
						Mappings []struct {
							PageSlug string `json:"pageSlug"`
							PageType string `json:"pageType"`
						} `json:"mappings"`
					} `json:"catalogNs"`
					OfferMappings []interface{} `json:"offerMappings"`
					Price         struct {
						TotalPrice struct {
							DiscountPrice   int    `json:"discountPrice"`
							OriginalPrice   int    `json:"originalPrice"`
							VoucherDiscount int    `json:"voucherDiscount"`
							Discount        int    `json:"discount"`
							CurrencyCode    string `json:"currencyCode"`
							CurrencyInfo    struct {
								Decimals int `json:"decimals"`
							} `json:"currencyInfo"`
							FmtPrice struct {
								OriginalPrice     string `json:"originalPrice"`
								DiscountPrice     string `json:"discountPrice"`
								IntermediatePrice string `json:"intermediatePrice"`
							} `json:"fmtPrice"`
						} `json:"totalPrice"`
						LineOffers []struct {
							AppliedRules []interface{} `json:"appliedRules"`
						} `json:"lineOffers"`
					} `json:"price"`
					Promotions struct {
						PromotionalOffers []struct {
							PromotionalOffers []struct {
								StartDate       time.Time `json:"startDate"`
								EndDate         time.Time `json:"endDate"`
								DiscountSetting struct {
									DiscountType       string `json:"discountType"`
									DiscountPercentage int    `json:"discountPercentage"`
								} `json:"discountSetting"`
							} `json:"promotionalOffers"`
						} `json:"promotionalOffers"`
						UpcomingPromotionalOffers []interface{} `json:"upcomingPromotionalOffers"`
					} `json:"promotions"`
				} `json:"elements"`
				Paging struct {
					Count int `json:"count"`
					Total int `json:"total"`
				} `json:"paging"`
			} `json:"searchStore"`
		} `json:"Catalog"`
	} `json:"data"`
	Extensions struct {
	} `json:"extensions"`
}
