package raiderio

import "time"

type AutoGeneratedErrorMessage struct {
	StatusCode int    `json:"statusCode"`
	Error      string `json:"error"`
	Message    string `json:"message"`
}

type AutoGeneratedActiveAffixes struct {
	Region         string `json:"region"`
	Title          string `json:"title"`
	LeaderboardURL string `json:"leaderboard_url"`
	AffixDetails   []struct {
		ID          int    `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description"`
		WowheadURL  string `json:"wowhead_url"`
	} `json:"affix_details"`
}

type AutoGeneratedPlayerInfo struct {
	Name                     string    `json:"name"`
	Race                     string    `json:"race"`
	Class                    string    `json:"class"`
	ActiveSpecName           string    `json:"active_spec_name"`
	ActiveSpecRole           string    `json:"active_spec_role"`
	Gender                   string    `json:"gender"`
	Faction                  string    `json:"faction"`
	AchievementPoints        int       `json:"achievement_points"`
	HonorableKills           int       `json:"honorable_kills"`
	ThumbnailURL             string    `json:"thumbnail_url"`
	Region                   string    `json:"region"`
	Realm                    string    `json:"realm"`
	LastCrawledAt            time.Time `json:"last_crawled_at"`
	ProfileURL               string    `json:"profile_url"`
	ProfileBanner            string    `json:"profile_banner"`
	MythicPlusScoresBySeason []struct {
		Season string `json:"season"`
		Scores struct {
			All    float64 `json:"all"`
			Dps    float64 `json:"dps"`
			Healer int     `json:"healer"`
			Tank   int     `json:"tank"`
			Spec0  float64 `json:"spec_0"`
			Spec1  int     `json:"spec_1"`
			Spec2  int     `json:"spec_2"`
			Spec3  int     `json:"spec_3"`
		} `json:"scores"`
	} `json:"mythic_plus_scores_by_season"`
	MythicPlusBestRuns []struct {
		Dungeon             string    `json:"dungeon"`
		ShortName           string    `json:"short_name"`
		MythicLevel         int       `json:"mythic_level"`
		CompletedAt         time.Time `json:"completed_at"`
		ClearTimeMs         int       `json:"clear_time_ms"`
		NumKeystoneUpgrades int       `json:"num_keystone_upgrades"`
		MapChallengeModeID  int       `json:"map_challenge_mode_id"`
		Score               float64   `json:"score"`
		Affixes             []struct {
			ID          int    `json:"id"`
			Name        string `json:"name"`
			Description string `json:"description"`
			WowheadURL  string `json:"wowhead_url"`
		} `json:"affixes"`
		URL string `json:"url"`
	} `json:"mythic_plus_best_runs"`
}
