package raiderio

type AutoGeneratedActiveAffixes struct {
	Region         string `json:"region"`
	Title          string `json:"title"`
	LeaderboardURL string `json:"leaderboard_url"`
	AffixDetails   []struct {
		ID          int    `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description"`
		WowheadURL  string `json:"wowhead_url"`
	} `json:"affix_details"`
}
