name: rebuild bot with new version
on:
  workflow_dispatch:
jobs:
  rebuild:
    name: rebuild
    runs-on: ubuntu-latest
    steps:
    - name: execute remote ssh commands
      uses: appleboy/ssh-action@v0.1.7
      with: 
        host: ${{ secrets.BOT_HOST }}
        username: ${{ secrets.BOT_USERNAME }}
        key: ${{ secrets.PEM_KEY }}
        script: |
          cd /var/opbbot 
          git pull
          docker build . --tag=opb_bot
          docker container stop opb_bot
          docker container rm opb_bot
          docker run --name opb_bot -p='8080:8080' -d --restart=on-failure:10 -v '/var/opbbot/bot.db:/app/bot.db' opb_bot
          message=$(git show -s --format='%an <%ae> %cD\nCommit: %h\nMessage: %s')
          curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "message=$message" http://localhost:8080/version_update
        
